config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#show'

  resources :recipes
  resources :meal_plans

  # def index
  #   @recipes = current_user.recipes.order(:id)
  # end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :meal_plan, inverse_of: :meals
  belongs_to :recipe
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  belongs_to :user
  has_many :meals, -> { order(:date) }, inverse_of: :meal_plan, dependent: :destroy

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :user, presence: true

  accepts_nested_attributes_for :meals

  def build_meals
    user_recipe_ids = user.recipes.pluck(:id)

    (start_date..end_date).each do |date|
      unused_recipe_ids = user_recipe_ids - meals.map(&:recipe_id)

      available_recipe_ids = if unused_recipe_ids.empty?
                               user_recipe_ids
                             else
                               unused_recipe_ids
                             end

      meals.build(date: date, recipe_id: available_recipe_ids.sample)
    end
  end

  def to_s
    "#{start_date} - #{end_date}"
  end
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :description, presence: true
  validates :user, presence: true

  def to_s
    name
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Clearance::User
  has_many :recipes
  has_many :meal_plans

  def recipe_options
    recipes.map do |recipe|
      [recipe.name, recipe.id]
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController
  before_action :require_login

  def index
    @current_meal_plan = current_user.meal_plans.where('start_date <= ? AND end_date >= ?', Date.today, Date.today).first
    @meal_plans = current_user.meal_plans.order('start_date DESC')
  end

  def show
    @meal_plan = current_user.meal_plans.find(params[:id])
  end

  def new
    @meal_plan = current_user.meal_plans.build(
      start_date: params[:start_date] || Date.today,
      end_date: params[:end_date] || Date.today + 6
    )

    @meal_plan.build_meals
  end

  def create
    @meal_plan = current_user.meal_plans.build(meal_plan_params)

    if @meal_plan.save
      redirect_to meal_plan_path(@meal_plan), notice: 'Meal plan created!'
    else
      @errors = @meal_plan.errors.full_messages
      render :new
    end
  end

  def edit
    @meal_plan = current_user.meal_plans.find(params[:id])
  end

  def update
    @meal_plan = current_user.meal_plans.find(params[:id])

    if @meal_plan.update(meal_plan_params)
      redirect_to meal_plan_path(@meal_plan), notice: 'Meal plan updated!'
    else
      @errors = @meal_plan.errors.full_messages
      render :edit
    end
  end

  def destroy
    @meal_plan = current_user.meal_plans.find(params[:id])
    @meal_plan.destroy
    redirect_to meal_plans_path, notice: 'Deleted Meal Plan!'
  end

  private

  def meal_plan_params
    params.require(:meal_plan).permit(
      :start_date,
      :end_date,
      meals_attributes: %i[
        id
        date
        recipe_id
      ]
    )
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :require_login
  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe = current_user.recipes.find(params[:id])
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to recipe_path(@recipe), notice: 'Recipe Created!'
    else
      @errors = @recipe.errors.full_messages
      render :new
    end
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
  end

  def update
    @recipe = current_user.recipes.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: 'Recipe Updated!'
    else
      @errors = @recipe.errors.full_messages
      render :edit
    end
  end

  def destroy
    recipe = current_user.recipes.find(params[:id])
    recipe.destroy
    redirect_to recipes_path, notice: "Deleted Recipe: #{recipe.name}"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def show; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <% if signed_in? %>
        Signed in as: <%= current_user.email %>
        <%= button_to 'Sign out', sign_out_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign in', sign_in_path %>
      <% end %>
    </header>

    <section>
      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>

      <%= yield %>
    </section>
  </body>
</html>

app/views/meal_plans/_form.html.erb
<%= render partial: "shared/errors"%>

<%= form_for @meal_plan do |form| %>
  <%= form.hidden_field :start_date %>
  <%= form.hidden_field :end_date %>

  <div class="meals">
    <%= form.fields_for :meals do |meal_fields| %>
      <div class="meal">
        <%= meal_fields.hidden_field :id %>
        <%= meal_fields.hidden_field :date %>
        <p><%= meal_fields.object.date.to_s %></p>
        <div class="form-control">
          <%= meal_fields.label :recipe_id %>
          <%= meal_fields.select :recipe_id, current_user.recipe_options %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meal_plans/edit.html.erb
<h1>Edit Meal Plan: <%= @meal_plan %></h1>

<%= render(partial: "form") %>

app/views/meal_plans/index.html.erb
<h1>Meal Plans</h1>

<% if @current_meal_plan.present? %>
  <h2>Current Meal Plan</h2>

  <div>
    <ul class="meals">
      <% @current_meal_plan.meals.each do |meal| %>
        <li class="meal">
          <%= meal.date %> - <%= link_to meal.recipe.to_s, recipe_path(meal.recipe) %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<h3>All Meal Plans</h3>

<% @meal_plans.each do |meal_plan| %>
  <div class="meal-plan">
    <%= link_to meal_plan, meal_plan_path(meal_plan) %>
  </div>
<% end %>

<div class="actions">
  <%= link_to "New Meal Plan", new_meal_plan_path %>
</div>

app/views/meal_plans/new.html.erb
<h1>New Meal Plan</h1>

<%= form_for @meal_plan, url: new_meal_plan_path, method: "GET" do |form| %>
  <div class="form-control">
    <%= form.label :start_date %>
    <%= form.text_field :start_date, type: "date" %>
  </div>

  <div class="form-control">
    <%= form.label :end_date %>
    <%= form.text_field :end_date, type: "date" %>
  </div>

  <div class="action">
    <%= form.submit "Generate Plan" %>
  </div>
<% end %>

<%= render partial: "form" %>

app/views/meal_plans/show.html.erb
<h1>Meal Plan: <%= @meal_plan %></h1>

<h2>Meals</h2>

<ul class="meals">
  <% @meal_plan.meals.each do |meal| %>
    <li class="meal">
      <%= meal.date %> - <%= link_to meal.recipe, recipe_path(meal.recipe) %>
    </li>
  <% end %>
</ul>

<div class="actions">
  <ul class="recipe-actions">
    <li>
      <%= link_to "Edit Meal Plan", edit_meal_plan_path(@meal_plan) %>
    </li>
    <li><%= link_to "Delete", meal_plan_path(@meal_plan), data: {
      confirm: "Are you sure you want to delete meal plan: #{@meal_plan}?",
    }, method: :delete %></li>
  </ul>
<div>

app/views/recipes/_form.html.erb
<%= render partial: "shared/errors"%>
<%= form_for @recipe do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render partial: "form" %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<div>
  <%= link_to"New Recipe", new_recipe_path %>
</div>

<div class="recipes">
  <% @recipes.each do |recipe| %>
  <div class="recipe">
    <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
    <p><%= recipe.description %></p>
    <ul class="recipe-actions">
      <li><%= link_to "Edit", edit_recipe_path(recipe) %></li>
      <li>
        <%= link_to "Delete", recipe_path(recipe), data: {confirm: "Are you sure
        you want to delete: #{recipe.name}?"}, method: :delete %>
      </li>
    </ul>
  </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render partial: "form" %>

app/views/recipes/show.html.erb
<h1> <%= @recipe.name%> </h1>

<h2> Description: </h2>

<p> <%= @recipe.description %> </p>

<div>
 <ul class='recipe-actions'>
 <li><%= link_to "Back", recipes_path %></li>
 <li><%= link_to "Edit", edit_recipe_path(@recipe) %></li>
      <li>
        <%= link_to "Delete", recipe_path(@recipe), data: {confirm: 'Are you sure
        you want to delete: #{recipe.name}?'}, method: :delete %>
      </li>
 </ul>
</div>

app/views/shared/_errors.html.erb
<% if @errors.present? %>
<div class="errors">
  <ul>
    <% @errors.each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/welcome/show.html.erb
<h1>Welcome</h1>